name: Extract content ID
description: Extract content_id from issue
inputs:
  issue-number:
    description: "Issue number"
    required: true
  github-token:
    description: 'access token to do github requests'
    required: true
outputs:
  content-id:
    description: 'issue content_id'
    value: ${{ steps.parse.outputs.content-id }}
runs:
  using: 'node16'
  main: 'dist/index.js'

